---
- name: Install and Configure NTP
  hosts: pis
  tasks:
  - name: Install NTP
    apt: name=ntp update_cache=yes
  - name: Copy the ntp.conf template file
    template: src=ntp.conf.j2 dest=/etc/ntp.conf
    notify:
      - restart ntp
  handlers:
  - name: restart ntp
    service: name=ntp state=restarted
